src/locales/en-US.json, src/views/Operations/ServerPowerOperations/BiosSettings.vue
- The options:
Default partition environment, AIX/LINUX partition boot mode
and IBM i partition boot mode are only enabled when the system is
non HMC-managed. Hence updated the text in the documentation section
that suggested the same.
- BQ defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW555796
=> Updated the text of server power ops documentation

src/views/Operations/ServiceLoginConsoles/ServiceLoginConsoles.vue
We were told to make the connection status logic for
the Hypervisor console be the same as the Host console.
The previous logic was incorrect because the Hypervisor
console does open long before PHYP STANDBY.
-Changed the connection status logic of Hypervisor
console to be the same as the Host console.
Signed-off-by: Sandeepa Singh [sandeepa.singh@ibm.com](mailto:sandeepa.singh@ibm.com)
BQ Ref
[SW555293](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW555293) : FTC1030:Everest:Hypervision console status showing as Disconnect
=> Changed connection status logic for Hypervisor console

src/views/Overview/OverviewDumps.vue
Remove dump download option from overview page
BQ defect:
[SW553721](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW553721) : FVTR1020:Rainier:GUI: Overview page Dumps information Download link doesn't download the actual dumps available
=> Remove dump download option from overview page

src/locales/en-US.json, src/views/SecurityAndAccess/UserManagement/ModalSettings.vue
Added help text on user management page to let the user know that if AccountLockoutThreshold (Max failed login attempts before locking user) is set to zero then the user will never be locked.
=> Add text on user management page

src/views/SecurityAndAccess/Ldap/Ldap.vue
- When the CA Certificate and LDAP Certificate are present, We can set the Secure LDAP using SSL checkbox value as true or false.
- When either of the two are NOT present, the checkbox is not editable and also the checkbox value must be false.
- BQ defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW555139
=> Fixed Secure LDAP using SSL checkbox value

src/locales/en-US.json, src/views/ProfileSettings/ProfileSettings.vue, src/views/SecurityAndAccess/Ldap/Ldap.vue, src/views/Settings/DateTime/DateTime.vue, src/views/Settings/PowerRestorePolicy/PowerRestorePolicy.vue
For consistency on the GUI, the save settings button has been renamed to save
=> Rename button the save settings button

src/store/modules/Authentication/AuthenticanStore.js
- In the scenario of rare cases, If login is successful but
unable to authenticate the user and fails to proceed, there is
no information and confuses the user. Hence, a back-up error
message is added here.
- BQ defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW555861
=> Error message displayed if fails to authenticate the user

src/locales/en-US.json, src/store/modules/HardwareStatus/AssemblyStore.js, src/store/modules/HardwareStatus/BmcStore.js, src/store/modules/HardwareStatus/ChassisStore.js, src/store/modules/HardwareStatus/FanStore.js, src/store/modules/HardwareStatus/MemoryStore.js, src/store/modules/HardwareStatus/PcieSlotsStore.js, src/store/modules/HardwareStatus/ProcessorStore.js, src/store/modules/HardwareStatus/SystemStore.js, src/views/HardwareStatus/Inventory/InventoryServiceIndicator.vue, src/views/HardwareStatus/Inventory/InventoryTableAssembly.vue, src/views/HardwareStatus/Inventory/InventoryTableBmcManager.vue, src/views/HardwareStatus/Inventory/InventoryTableChassis.vue, src/views/HardwareStatus/Inventory/InventoryTableDimmSlot.vue, src/views/HardwareStatus/Inventory/InventoryTableFans.vue, src/views/HardwareStatus/Inventory/InventoryTablePcieSlots.vue, src/views/HardwareStatus/Inventory/InventoryTableProcessors.vue
Success toast messages were missing on Inventory page. 
- Added success toast message for toggle switches on inventory page for consistency across GUI.
BQ defect link: [SW556549 ](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW556549): FTC1030: Everest: No notification after changing identify led on hardware inventory page
=> Add success toast

src/views/ResourceManagement/Memory/Memory.vue
- Editable section of the Memory page was HMC-managed dependent, Made it independent.
- BQ defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=FW725233
- BQ defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW555488
=> Memory page made HMC-managed independent

src/components/Global/InfoTooltipPassword.vue, src/locales/en-US.json
Updated the help text for password. The new password must have characters from at least two classes: lowercase letters, uppercase letters, digits, and other characters.
=> Update password helptext

src/store/modules/Settings/NetworkStore.js
While trying to modify the eth1 ip address, the system was going into bad state. 
- Fixed the patch call which was resulting in error when modifying ip address for second time.
BQ defect: [SW556598](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW556598) : FTC1030:Rainier:Network:GUI- Modifying eth1 IP multiple times cause eth0 to lose its network configuration
=> Fix network eth1 error

src/store/modules/HardwareStatus/SensorsStore.js
- Sensors page was not updating on refresh. On refresh now, we are removing the values present and adding to the table from the beginning.
- BQ defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW556657
=> Sensors table now updating on refresh

src/views/SecurityAndAccess/Ldap/Ldap.vue
- Secure LDAP was not getting disabled when the LDAP authentication disables. This change fixes this problem
- BQ defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW556683
=> Secure LDAP is disabled when LDAP authentication disables

src/locales/en-US.json, src/views/Settings/DateTime/DateTime.vue
The date and time page will be greyed out when the host is up or ipling.
- Add help text  for NTP
BQ defect link : 
- [SW556675](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW556675) : GUI: Date and time page must be read-only when Host is up or ipling
- [SW556677](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW556677) : GUI: Notify user the NTP server system is configured to
=> Disable date and time page when host is up or ipling

src/env/components/AppNavigation/ibm.js
- Services consoles page was showing up for the read-only users,
This is fixed by filtering the restricted users.
BQ defect : https://w3.rchland.ibm.com/projects/bestquest/?defect=SW556467
=> Removed Service consoles page for read-only users

src/locales/en-US.json, src/views/ResourceManagement/SystemParameters/FrequencyCap.vue
Added a info tooltip to frequency cap to help user when the frequency cap is disabled
BQ defect: 
[SW557159](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW557159 ) : GUI: System Parameters: Add help text to Frequency cap for why it might be disabled
=> Add info tooltip to frequency cap

src/store/modules/GlobalStore.js, src/views/Settings/HardwareDeconfiguration/MemoryDimms.vue, src/views/Settings/HardwareDeconfiguration/ProcessorCores.vue
Disabled the switches when the logged in user is read-only.
BQ defect : [SW555862 ](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW555862): FVTR1020.10:Rainier:CDM GUI:Incorrect error message displayed for read only user when configuring/deconfiguring dimm/core in HW deconfiguration page
=> Read only user will not be able to toggle switches

src/locales/en-US.json, src/store/modules/SecurityAndAccess/PoliciesStore.js
- On Disable SSH, there is a toast message which says, "Successfully disabled BMC shell (via SSH), Please allow 15 seconds for the disable to become effective."
- BQ defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW533682
=> Additional message added on Disable SSH

src/views/ProfileSettings/ProfileSettings.vue, src/views/SecurityAndAccess/UserManagement/UserManagement.vue
- Password maxLimit for IMPI AccountType is set to 20 else it is set based on the redfish response(64)
- BQ defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW556104
=> Updated password Max Limit

src/locales/en-US.json, src/store/modules/Authentication/AuthenticanStore.js, src/views/Login/Login.vue
-   In the scenario of rare cases, If login is successful but
unable to authenticate the user and fails to proceed, there is
error message "User unauthorized". Else if even unable to login, there is
error message "Invalid username or password" displayed.
-   BQ defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW555861
=> New Error message displayed if fails to authenticate the user

src/locales/en-US.json, src/views/SecurityAndAccess/UserManagement/TableRoles.vue, src/views/SecurityAndAccess/UserManagement/UserManagement.vue
- Status values were displayed directly from the redfish, Hence added the possible values to the translation file and using them.
- Roles headers were taken directly, Hence added them to the translation file and using them.
=> Added Status and roles values to the translation file

src/views/Login/Login.vue
- When the translation of the Project is set to a language, Evey thing else except the title of the page was getting translated, Now Even the title is getting translated with this change
=> Title translation

src/views/ResourceManagement/CapacityOnDemand/CapacityOnDemandOrderInfo.vue
- In the Capacity on demand page, we were displaying the value from model. Now, that the new System Anchor is available under Licenses, the Serial Number is being displayed in the UI.
- BQ defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW552204
=> Displaying System Anchor value

src/views/SecurityAndAccess/UserManagement/UserManagement.vue
- Max limit was set based on the Current logged in user. But now the max limit is now set based on the selected user. Hence, there won't be any error message now.
- BQ defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW557769
=> Added max limit based on selected user

src/views/Overview/OverviewServer.vue
Remove service login label for read only user as it will show disabled for read only user and it might be confusing for the user.
BW defect : [SW556469 ](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW556469): FTC1030:Rainier:GUI: Service Login status comes as disabled in overview page with readonly user
=> Remove service login label for read only user

src/views/Login/Login.vue
- Initially it was refreshing twice after the login to GUI, this is fixed.
- BQ defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW557765
=> Refresh only once after login

src/components/AppHeader/AppHeader.vue, src/layouts/LoginLayout.vue
When loading the IPS logo, the original width value is too small, which is not suitable for the IPS logo.
=> ips-localization: Change the width property size

src/views/Operations/ServerPowerOperations/BiosSettings.vue
Fix translation defect for server power ops. Labels of the `power setting description ` table are now translatable.
=> Fix translation defect for server power ops

src/locales/en-US.json, src/views/HardwareStatus/Inventory/Inventory.vue, src/views/HardwareStatus/Inventory/InventoryTablePcieSlots.vue
- Tab names were taken only in English, Hence added these names in the translation file.
- Slot type is now taken from the translation file in the PCIe slots table in Inventory page.
=> Tab names translated in Inventory page

src/locales/en-US.json, src/views/SecurityAndAccess/UserManagement/UserManagement.vue
- Previously the values were taken from the redfish response, Now we are comparing the value coming from the redfish and then using the equivalent value from the translation file for privilege property in the User management page.
=> Using privilege values from the translation file

src/store/modules/Settings/HardwareDeconfigurationStore.js
- Previously the values were taken from the redfish response, Now we are comparing the value coming from the redfish and then using the equivalent value from the translation file for Deconfiguration type for Dimms and cores in Hardware deconfiguration page.
=> Deconfiguration type is taken from translation file

src/views/Login/Login.vue
This reverts commit 5105bc3af9867dc8c8b2f7747c8b902bb4e7c367.
This revert fixes https://w3.rchland.ibm.com/projects/bestquest/?defect=SW558381
https://github.com/ibm-openbmc/webui-vue/pull/42 was a fix for GUI refreshing twice (https://w3.rchland.ibm.com/projects/bestquest/?defect=SW557765) 
The fix broke the HMC proxy to the GUI. This was reported only breaking on 1030 and in the last month. 
The HMC proxy is accessible via "Connections and operations" -> "Launch Advanced System Management (ASM)". 
https://github.ibm.com/openbmc/webui-vue/pull/208
https://github.ibm.com/openbmc/webui-vue/pull/226
were the original comments to enable the proxy 
With this revert we should reopen https://w3.rchland.ibm.com/projects/bestquest/?defect=SW557765 but I think SW557765 is a lot less worse than …
=> SW558381: Revert "Refresh only once after login (#42)"

src/env/assets/styles/_ibm.scss, src/views/ResourceManagement/CapacityOnDemand/CapacityOnDemandActivation.vue
When some buttons are described in Chinese, the shape of the button will change due to word wrapping.
=> Fix Chinese line break problem

src/views/ChangePassword/ChangePassword.vue
After executing a factory reset, reset the password. Even if the entered password meets the requirements of the password complexity, it will prompt that the password is wrong, and then click the reset button again, and it will be successful.
Cause of the problem: When the password is reset, the UI will send the patch and get methods synchronously. Even if the patch method is not completed, the get method will be executed, and 403 will be returned at this time.
So the patch method should be executed first, and the get method should be executed after waiting for the correct return value.
Tested:
After factory reset, reset the password. After entering the correct password, click the reset button, and it will prompt that the reset is successful.
=> Fix reset password error prompt password error

src/store/modules/ResourceManagement/LicenseStore.js
Because compared with the current Host Fw and the 079 Host Fw, after the host is turned on, there are 5 more licenses entries [1], and all licenses entries are hard-coded in webui-vue, so these 5 entries are temporarily filtered here Data to prevent GUI interface from displaying abnormally.
[1]
P05 Virtual Tier
P10 Virtual Tier
P20 Virtual Tier
P30 Virtual Tier
System Anchor
=> Filter redundant licenses entry

src/store/modules/HardwareStatus/ConcurrentMaintenanceStore.js
- The values was not updating for Operator panel base maintenance and Operator panel LCD maintenance. The values in the label was not updating as per the values in the switch. It is fixed here.
BQ link:  https://w3.rchland.ibm.com/projects/bestquest/?defect=PE00F0NL
=> Labels now updating in Concurrent maintenance page

src/views/Operations/ServerPowerOperations/BiosSettings.vue
After switching to a non-English language and bmc is taken over by HMC, `Server firmware start policy` will not be displayed, because it is hard-code, so only English is supported.
This commit is to use a variable to filter `Server firmware start policy` instead of hardcoding.
Tested: Manually changed to non-English, built webui-vue successfully and passes.
=> Fix server firmware start policy
